### ISSUE TITLE
Fix: Template might fail the CI due to some latest CI actions update

### ISSUE THREAD

**Issue by sleepylee** [nimblehq/elixir-templates#330]
## Issue

<img width="1337" alt="Image" src="https://github.com/user-attachments/assets/7af9bbee-2caa-4025-b054-0de328119a4f" />

New users may fall in this issue, the reason is that they changed again from `erlef/setup-elixir@v1` to `erlef/setup-beam@v1`
Also, new config might be required, here is my suggestion:

```
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
          rebar-version: ${{ env.REBAR_VERSION }}
          hexpm-mirrors: |
            https://builds.hex.pm
            https://cdn.jsdelivr.net/hex
```

 
## Expected

CI should work
